Home UI Implementation
BuildForSDG/Team-203-TranSafe pull request #41
Opened 2020-05-27 17:46 UTC by penbosso

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.
Homepage UI and side menu implemented with no dependencies.
Fix speedometer display for all device screen sizes 
Resolve codacity issues
Modify the speed gauge to have only one handle which will point to the the current speed of the user
Calibrate the speed gauge display at interval of 20 from 0 to 170

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #15 #39 # 40#30 #29 #28 #27

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.
The UI implementation has been tested in edge and group browser with chrome dev. tool toggle to mobile view.

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Screenshots (if applicable, else remove this line / section)
![image](https://user-images.githubusercontent.com/25876829/83054416-e7c53180-a041-11ea-898a-05616f09baba.png)

## Checklist:

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have added necessary inline code documentation
- [ x ] I have added tests that prove my fix is effective and that this feature works
- [ x ] New and existing unit tests pass locally with my changes

2020-05-28 21:37 UTC, mickeymond approved these changes

2020-05-28 21:41 UTC, ianakoto requested changes
Please Add a track button beside the speed gauge  and make the user able to differentiate distinctly what his current speed is and the speed limit

2020-05-29 15:45 UTC, Quame-Magma approved these changes
Cool

2020-05-29 23:30 UTC, ErnestinaTawiah approved these changes

2020-05-30 05:57 UTC, merged