Ref back end tran safe
BuildForSDG/Team-203-TranSafe pull request #64
Opened 2020-06-07 17:47 UTC by Arshir

## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Documentation #63 

## How Has This Been Tested?
Proof- reading of the information captured to correct spelling error, grammatical errors, and ensure the information is correct , accurate and concise.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-06-07 17:54 UTC, Quame-Magma requested changes
The full name is Arnold Anyor, not Anold Quame. Please check and correct it

2020-06-09 15:50 UTC, ianakoto approved these changes

2020-06-09 17:51 UTC, Quame-Magma approved these changes

2020-06-12 03:59 UTC, ErnestinaTawiah reviewed
great

2020-06-12 05:07 UTC, mickeymond approved these changes

2020-06-12 22:34 UTC, merged